services:
  # 前端服务
  frontend:
    build:
      context: ./moyushuang-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - moyushuang-network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ./moyushuang-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./moyushuang-backend/.env.production
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - moyushuang-network
    restart: unless-stopped

  # MySQL数据库
  mysql:
    image: mysql:8.0
    env_file:
      - ./moyushuang-backend/.env.production
    environment:
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    networks:
      - moyushuang-network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5
      interval: 5s
      start_period: 10s
    networks:
      - moyushuang-network
    restart: unless-stopped

# 网络配置
networks:
  moyushuang-network:
    driver: bridge

# 数据卷
volumes:
  mysql_data:
  redis_data: